### ISSUE TITLE
Add register classes

### ISSUE THREAD

**Issue by tudortimi** [pyuvm/pyuvm#6] opened 2021-09-20 11:54 UTC

**Comment by tudortimi** [comment] 2021-09-20 11:56
I need the register model classes for a blog post I'm planning. I opened this issue as a TODO for myself to implement this.

**Comment by raysalemi** [comment] 2021-09-20 12:22
I think that would be a great project. Are you going to implement the UVM
RAL?

**Comment by tudortimi** [comment] 2021-09-21 09:48
Yes, though this is too much for a single PR. I'll split it up into small bits.

**Comment by raysalemi** [comment] 2022-01-04 16:07
For future reference: https://semiconductorclub.com/how-uvm-ral-works/

No better place to store it.

**Comment by EngRaff92** [comment] 2022-03-12 22:13
Hello all I just enhanced the reg field and added the reg item for future write read support. Working on men and uvm reg.

**Comment by raysalemi** [comment] 2022-03-12 23:58
> Hello all I just enhanced the reg field and added the reg item for future write read support. Working on men and uvm reg. should I deliver firstly and then testing ? I believe the best approach would be to test it out on my side first just to be sure there is no hidden bug. On top of that pyvsc is required at moment for randomisation support is that ok ?

Thanks!

Please include the testing in the testing system so that we can run it with tox.  I agree with testing it on your side first then adding the tests to the `tests` directory.

As for randomization, I'm planning to use **pyquesta** for randomization sometimes, so it would be best if the randomization choice were not hardcoded.  But **pyvsc** is fine as an option.

**Comment by EngRaff92** [comment] 2022-03-13 09:12
Hello Ray thanks for the quick reply, sure I will probably not hard code the randomisation at moment (probably will add a switch on that). Keep you all posted soon with the release (there might be another just for further optimisations since I’m keep it as much as simple I can to smooth out the complexity). 

If you guys could kindly assign this to me as well so I can support.

Kind regards

**Comment by EngRaff92** [comment] 2022-05-22 11:09
General Update: Added files and tests on local pyuvm_ral_model branch:

- [ ]  register item
- [ ] pyvcs vs local randomisation decorator 
- [ ] register field
- [ ] pyvum_register
- [ ] adding write and read
- [ ] adding some checking mechanism (list of error enums)
- [ ] some initial code for register map and register block
- [ ] some initial code for pyvum_mem ready to be pushed as well

Current regression result
Results (0.26s):
      64 passed
      12 failed
         - test_pyuvm_ral.py:121 test_reg_field_configure
         - test_pyuvm_ral.py:132 test_reg_field_is_volatile
         - test_pyuvm_ral.py:142 test_simple_reg_model
         - test_pyuvm_reg.py:121 test_reg_field_configure
         - test_pyuvm_reg.py:132 test_reg_field_is_volatile
         - test_pyuvm_reg.py:142 test_simple_reg_model
         - test_pyuvm_reg_block.py:121 test_reg_field_configure
         - test_pyuvm_reg_block.py:132 test_reg_field_is_volatile
         - test_pyuvm_reg_block.py:142 test_simple_reg_model
         - test_pyuvm_reg_map.py:121 test_reg_field_configure
         - test_pyuvm_reg_map.py:132 test_reg_field_is_volatile
         - test_pyuvm_reg_map.py:142 test_simple_reg_model

**Comment by raysalemi** [comment] 2022-05-22 13:10
Please tell me more about pyvcs.  Does it do the same thing as pyquesta?

Ray

**Comment by EngRaff92** [comment] 2022-05-22 14:42
I did not use pyquesta honestly so not sure about the differences if any. Nevetheless, I used quite often PYVCS in my project and I do not feel I miss SV randomisation or solver since pyvcs works roughly in the same way. from documentation: 

"PyVSC is a Python library that implements random verification-stimulus generation and coverage collection. PyVSC provides this capability in two forms: an object-oriented Model API, and a Python-embedded domain-specific language built on top of the Model API. This allows coverage and randomization features to be programmatically built, defined with user-friendly constructs, or defined using a mix of the two."

website: https://pyvsc.readthedocs.io/en/latest/introduction.html

one example of usage I do:
![image](https://user-images.githubusercontent.com/40317961/169700915-5a64278d-608e-4486-b317-27e6def209f8.png)

hope this clarifies. The way is used into the RAL is by declaring every REG as rand objects so that the main values can be randomised before issuing a write.

Raffaele

**Comment by raysalemi** [comment] 2022-05-22 16:22
That's funny I thought it was pyvcs not pyvsc.  

I thought that someone had written a link to VCS.

**Comment by EngRaff92** [comment] 2022-05-22 16:27
Sorry for the typo

**Comment by nicotrozzo** [comment] 2023-03-30 21:26
Hi! Any updates on this? It would be really nice to have it integrated in `pyuvm`!

**Comment by EngRaff92** [comment] 2023-03-30 22:41
Hello, yep keep working on that but as side projects along with others. Do you have any estimated time to have it done ? Regards

**Comment by raysalemi** [comment] 2023-03-31 02:44
I may take a crack at it this summer vacation. But I'm also creating a MATLAB class for my high school and that is top priority.

**Comment by crteja** [comment] 2023-07-21 13:33
> General Update: Added files and tests on local pyuvm_ral_model branch:
> 
> * [x]   register item
> * [x]  pyvcs vs local randomisation decorator
> * [x]  register field
> * [x]  pyvum_register
> * [x]  adding write and read
> * [x]  adding some checking mechanism (list of error enums)
> * [x]  some initial code for register map and register block
> * [x]  some initial code for pyvum_mem ready to be pushed as well
> * [ ]  backdoor read and write
> * [ ]  HDL_PATH and HDL_PATH slice
> * [ ]  full pyvum_mem features
> * [ ]  autogen pyuvm_mem and pyuvm_paths for backdoor
> * [ ]  byte addressable write and read
> * [ ]  adding full example of Pyvum_Ral usage
> * [ ]  autogen DOC using sphinx
> 
> Current regression result Results (0.26s): 64 passed 12 failed - test_pyuvm_ral.py:121 test_reg_field_configure - test_pyuvm_ral.py:132 test_reg_field_is_volatile - test_pyuvm_ral.py:142 test_simple_reg_model - test_pyuvm_reg.py:121 test_reg_field_configure - test_pyuvm_reg.py:132 test_reg_field_is_volatile - test_pyuvm_reg.py:142 test_simple_reg_model - test_pyuvm_reg_block.py:121 test_reg_field_configure - test_pyuvm_reg_block.py:132 test_reg_field_is_volatile - test_pyuvm_reg_block.py:142 test_simple_reg_model - test_pyuvm_reg_map.py:121 test_reg_field_configure - test_pyuvm_reg_map.py:132 test_reg_field_is_volatile - test_pyuvm_reg_map.py:142 test_simple_reg_model

@EngRaff92, I have added implementation for chapter 17 in UVM standard. you can probably use the enums declared in the file for RAL model (if not implemented already)

**Comment by EngRaff92** [comment] 2023-07-21 13:42
@crteja thanks for the support actually what do you mean by chapter 17? Any specific file from where I could grab and use your changes ? Regards and thanks again

**Comment by crteja** [comment] 2023-07-21 13:44
> @crteja thanks for the support actually what do you mean by chapter 17? Any specific file from where I could grab and use your changes ? Regards and thanks again

Sorry, forgot to include PR (https://github.com/pyuvm/pyuvm/pull/154) in earlier comment.

**Comment by EngRaff92** [comment] 2023-07-21 14:05
Great thanks

**Comment by raysalemi** [comment] 2023-07-21 15:10
The regression tests are failing on the PR.

**Comment by raysalemi** [comment] 2023-07-21 17:00
@crteja I have to admit that I have not looked at the UVM RAL yet. 

Do you have a sense of how close we are to completion?

**Comment by EngRaff92** [comment] 2023-07-21 17:08
All the changes I made are local at moment, planning on pushing something on git over the weekend (sorry for this delays) I will update the table of completion if not this weekend the next for sure. In terms of major completion the single reg + item + draft of adapter and prediction are there. The major missing features are back door and maps and then the main wrapper block. Sorry again for the delay in getting this done

**Comment by raysalemi** [comment] 2023-07-21 17:22
> All the changes I made are local at moment, planning on pushing something on git over the weekend (sorry for this delays) I will update the table of completion if not this weekend the next for sure. In terms of major completion the single reg + item + draft of adapter and prediction are there. The major missing features are back door and maps and then the main wrapper block. Sorry again for the delay in getting this done

I appreciate all you're doing and any time you can give!

I was just curious.  I plan to make pyuvm 3.0 the first version with RAL in it.

**Comment by EngRaff92** [comment] 2023-07-21 17:40
No worries happy to help and contribute. And what is the estimated time for this release? Sorry for asking but sometimes is quite great having a deadline.

**Comment by raysalemi** [comment] 2023-07-21 17:53
It makes sense to release it before the last week of August. I'll be back in school after that and will not have the time to manage a new release.

**Comment by raysalemi** [comment] 2023-07-21 17:53
Though, maybe we just release the dev version in August and let people try it out?

**Comment by EngRaff92** [comment] 2023-07-21 18:21
End of August makes sense to me. @crteja absolutely I can share work would be great. Yes I will do a commit in this case on a separate dev branch and we will be starting from there what do you think ?

**Comment by crteja** [comment] 2023-07-21 18:26
That would be great.

**Comment by raysalemi** [comment] 2023-07-21 18:33
Any suggestions for an example project?  

Maybe the Wishbone 2 I2C block?

**Comment by crteja** [comment] 2023-07-21 18:41
I think any RTL project that works with `verilator` and `cocotb` should be fine as it makes writing a new example easy. It will also help more people tryout `pyuvm`.

**Comment by EngRaff92** [comment] 2023-07-21 21:10
I do use an apb reg rtl (4 registers with different right policies) to test sequencer given to the RAL + adapter (still not working anyway ) but at least I can test the prediction. We could anyway use the existing ALU in pyuvm by just adding some registered commands (op are stored into flops RW and result is RO)

**Comment by raysalemi** [comment] 2023-07-22 00:03
I love that register-driven TinyALU idea!

**Comment by EngRaff92** [comment] 2023-08-06 11:26
Hello all,

JUST FINISHED the commit RESUME:
pyuvm/s18_pyuvm_reg_block.py
delete mode 100644 pyuvm/s18_register_model.py
create mode 100644 pyuvm/s19_pyvum_reg_field.py
create mode 100644 pyuvm/s20_pyuvm_reg.py
create mode 100644 pyuvm/s21_pyuvm_reg_map.py
create mode 100644 pyuvm/s22_pyuvm_mem.py
create mode 100644 pyuvm/s23_pyuvm_reg_item.py
create mode 100644 pyuvm/s24_pyuvm_reg_includes.py
create mode 100644 pyuvm/s25_pyuvm_adapter.py
create mode 100644 pyuvm/s26_pyuvm_predictor.py
create mode 100644 pyuvm/s27_pyuvm_reg_pkg.py
delete mode 100644 tests/pytests/test_18_register_model.py
create mode 100755 tests/pytests/test_pyuvm_ral.py
create mode 100755 tests/pytests/test_pyuvm_reg.py
create mode 100755 tests/pytests/test_pyuvm_reg_block.py
create mode 100755 tests/pytests/test_pyuvm_reg_field.py
create mode 100755 tests/pytests/test_pyuvm_reg_map.py

Regression with 85 tests is passing 

There is still work todo (I left few TODOs around there), anyway even if few files are empty like the PYVUM_REG_MEM (I do prioritise the PYVUM_REG rather then the MEM to be honest), imo we could get it working smoothly by the end of the month. Sorry in advance for any MISTAKE or If I did not follow exactly the way PYVUM should be coded up. Anyway feel free to get back to me for any issue/query/doubt or any change required.

**Comment by raysalemi** [comment] 2023-08-06 13:01
Wow!  Is it ready to try the TinyALU example?

**Comment by EngRaff92** [comment] 2023-08-06 13:07
Unfortunately not yet, still finishing some work before getting ready for the RTL. Nevertheless I’m pretty confident it will be at the end of the month. Thanks

**Comment by HamzaShabbir517** [comment] 2023-09-17 06:00
@EngRaff92 is the RAL model completed as i have an RTL of AES peripheral which i want to test using pyuvm i am done with the framework only the RAL logic is remaining/

**Comment by EngRaff92** [comment] 2023-09-17 09:21
> @EngRaff92 is the RAL model completed as i have an RTL of AES peripheral which i want to test using pyuvm i am done with the framework only the RAL logic is remaining/

Hey @HamzaShabbir517 almost there I’m gonna give a big blast today as I did yesterday so most likely will be ready for last PR if not today next weekend. Regards

**Comment by raysalemi** [comment] 2023-09-17 10:36
Right now the RAL work is on a branch, but I will create a 3.0dev release on master when RAL is ready for people to try.

**Comment by HamzaShabbir517** [comment] 2023-09-17 10:51
Thanks for the information.

@ark010 please keep track of this issue this will help you in future

**Comment by PatrickCPE** [comment] 2023-10-02 15:45
Hi @raysalemi,

I'd like to use PyUVM for an upcoming project, and the RAL would extremely beneficial. 

**I'd be glad to help out with any finishing touches/examples/documentation you need. What still needs to be integrated for the RAL to be functional?**

**Comment by raysalemi** [comment] 2023-10-03 11:16
Hi Pat,

That would be great! @EngRaff92 is putting the final touches on it and I bet we need documentation. 

You can join the discussion here [Topic 161](https://github.com/pyuvm/pyuvm/discussions/161)

The RAL team is working on the `ral_dev` branch. 

I'll soon be releasing the 3.0dev version of **pyuvm** with RAL on it. 

Ray

**Comment by raysalemi** [comment] 2024-06-26 16:14
This issue has been overcome by events. There are new topics discussing it.

**Closed by raysalemi** 2024-06-26 16:14 UTC
Labels: enhancement
